name: terraform-checks

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Validate local lab
        working-directory: labs/00-local-basics
        run: |
          terraform init -backend=false
          terraform validate

      - name: Validate AWS lab
        working-directory: labs/01-s3-static-data
        run: |
          terraform init -backend=false
          terraform validate
